global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - dev01:9090
- job_name: storeapi
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - store-api:8000
